export const PING_BACKEND_SERVER = 'PING BACKEND SERVER'
export const LOAD_WEATHER = 'LOAD WEATHER'
export const LOAD_REAL_TIME_WEATHER = 'LOAD REAL-TIME WEATHER'
export const LOAD_FORECAST = 'LOAD FORECAST WEATHER'